services:
  spring-app:
    image: docconneting-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docsql
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass
      SPRING_REDIS_HOST: redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docsql
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
