input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  # message 안을 파싱해서 type 필드를 추출
  grok {
    match => { "message" => ".*type=%{WORD:type}.*" }
  }

  # 원하는 type만 남기고 나머지는 drop
  if !([type] in ["POINT_USAGE", "COUPON_USAGE", "POINT_REFUND"]) {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docconneting-logs-%{+YYYY.MM.dd}"  # 로그가 저장될 인덱스
  }
}