spring:
  application:
    name: docconneting
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  profiles:
    active: local

jwt:
  secret:
    key: rC1fZ3pYzPiNL2RzZHYtN3Q5MHJsT3pkZVNyT2lYa2M